### ISSUE TITLE
Update for 2022

### ISSUE THREAD

**Issue by njames** [nunomaduro/laracon-schedule#17]
So 2 options to update for 2022 Laracon:

1. Update the variables `$scheduling`, `$lightningTalks`, and `$community` with the 2022 data - job done

or 

2. create a json file called nnnn.json for each year with the data in it and add a --year parameter to the command defaulting to the current year. 

Thus next year you can composer update and add a new 2023.json file 

Which do you prefer?

**Comment by owenvoke** [comment]
I think updating the variables makes more sense 👍🏻

**Comment by nunomaduro** [comment]
https://github.com/nunomaduro/laracon-schedule/pull/16

**Comment by nunomaduro** [comment]
Thank you, but https://github.com/nunomaduro/laracon-schedule/pull/16 solves this issue.
