### ISSUE TITLE
Please add limitless solution

### ISSUE THREAD

**Issue by spresnac** [nunomaduro/laracon-schedule#5]
Using windows, i feel kinda mobbed-out 😭

Maybe you could ask on windows what timezone to use (a simple +1 as Europa/Berlin would do it). Or a config???

**Comment by cmanish049** [comment]
yes so sad it didn't work on my windows machine as well

**Comment by nunomaduro** [comment]
@spresnac @cmanish049 Can you test this: https://github.com/nunomaduro/laracon-schedule/pull/6?

**Comment by spresnac** [comment]
@nunomaduro Works for me now
![grafik](https://user-images.githubusercontent.com/3299107/111459681-4ff11b00-871b-11eb-99c9-c973990699e4.png)

**Comment by nunomaduro** [comment]
Merged and released.
