### ISSUE TITLE
File not exists (Windows)

### ISSUE THREAD

**Issue by spresnac** [nunomaduro/laracon-schedule#7]
![grafik](https://user-images.githubusercontent.com/3299107/111460800-b296e680-871c-11eb-88c0-4adfd1b8db38.png)

**Comment by spresnac** [comment]
This problem only comes up when i am NOT in the composer vendor directory!
When in the directoy, it works:
![grafik](https://user-images.githubusercontent.com/3299107/111461135-20dba900-871d-11eb-91d3-1c0514201bee.png)

**Comment by spresnac** [comment]
IMHO should there be a defined `Storage::disk()` in this line: https://github.com/nunomaduro/laracon-schedule/blob/32f78e8a635e509a6fefe338aa794cd1257d3798/app/Commands/SchedulingCommand.php#L152

**Comment by nunomaduro** [comment]
@spresnac Can you make a pull request? And test that same code in your machine?

**Comment by muath-ye** [comment]
You need to go to this path 
In my case, it is in windows
```/AppData/Roaming/Composer/vendor/nunomaduro/laracon-schedule```

and then run 
```composer install```
![image](https://user-images.githubusercontent.com/34031333/111467560-a1a69f00-8735-11eb-86d2-e6b1a45a2215.png)

It worked for me after installing composer dependencies.
![image](https://user-images.githubusercontent.com/34031333/111467659-be42d700-8735-11eb-801c-0fcb348ea53a.png)

**Comment by spresnac** [comment]
@nunomaduro pr is at you ;)

**Comment by nunomaduro** [comment]
Released.
